from alpine

RUN apk add --no-cache curl && \
    curl -LO https://github.com/tidwall/jj/releases/download/v1.2.2/jj-1.2.2-linux-amd64.tar.gz && \
    tar xzf jj-1.2.2-linux-amd64.tar.gz && mv jj-1.2.2-linux-amd64/jj .
