build:
	docker-image-tool.sh  -r annoyingllama -t 3.1.1-hadoop2.7-python3.8 -p Dockerfile build

push:
	docker-image-tool.sh  -r annoyingllama -t 3.1.1-hadoop2.7-python3.8 -p Dockerfile build

build-push:
	docker-image-tool.sh  -r annoyingllama -t 3.1.1-hadoop2.7-python3.8 -X -p Dockerfile build

