#!/usr/bin/env bash

set -x

PRESTO_COORDINATOR_URL=${PRESTO_COORDINATOR_URL:-"http://$PRESTO_PORT_8080_TCP_ADDR:$PRESTO_PORT_8080_TCP_PORT"}
MYSQL_URL=${MYSQL_URL:-"jdbc:mysql://$MYSQL_PORT_3306_TCP_ADDR:$MYSQL_PORT_3306_TCP_PORT/$MYSQL_DB"}
LOG_LEVEL=${LOG_LEVEL:-ERROR}

java -Ddw.prestoCoordinator=$PRESTO_COORDINATOR_URL \
     -Ddw.dataSourceFactory.driverClass=com.mysql.jdbc.Driver \
     -Ddw.dataSourceFactory.url=$MYSQL_URL \
     -Ddw.dataSourceFactory.user=$MYSQL_USER \
     -Ddw.dataSourceFactory.password=$MYSQL_PASSWORD \
     -Ddw.logging.level=$LOG_LEVEL \
     -server \
     -Duser.timezone=UTC \
     -cp build/libs/airpal-*-all.jar \
     com.airbnb.airpal.AirpalApplication \
     server \
     reference.yml
