dates = []
replace = false
s2s_networks = [
  "network1"
]

[s3]
  path = "s3n://your-bucket"

[hive]
  host = "localhost"
  port = 10000
  tables = [ "table1" ]
  cleanup_tables = [
    { name = "table1", months_ago = 3 }
  ]
