dates = []
replace = false

[s3]
  path = "s3n://your-bucket"

[hive]
  host = "localhost"
  port = 10000
  tables = [ "table1" ]
  cleanup_tables = [
    { name = "table1", months_ago = 3 }
  ]

[[hive.aggregate_tables]]
  name = "s2s_reports"
  key = "network"
  paths = [
    "path1"
  ]
[[hive.aggregate_tables]]
  name = "ml_reports"
  key = "network"
  paths = [
    "path2"
  ]
