name: Test Service Account Validity
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  SA-Validity:
    runs-on: ubuntu-latest
    steps:
      - name: Write service account key to file
        run: printf '%s' "${{ secrets.DATA_TEAM_GAR_SA_KEY }}" > $HOME/data_team_gar_sa.json

      - name: Print key to console for troubleshooting
        run: cat $HOME/data_team_gar_sa.json

      # - name: Authenticate with GCP
      #   run: gcloud auth activate-service-account --key-file=$HOME/data_team_gar_sa.json

      # - name: Set vgi-pn-277619 as default project
      #   run: gcloud config set project vgi-pn-277619

      # - name: List us-east4 artifact repositories
      #   run: gcloud artifacts repositories list --location=us-east4